### ISSUE TITLE
AgMT: Email notification : For a translator when a super-admin approves the request for admin access

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/vachan-api#107]
New feature description:
When a super-admin approves the admin -access request of a translator, the translator is to be notified via email the request for admin access has been approved.
This would help the translator  to be notified that his/her access privileges are now that of an admin, without having to login to the tool

**Comment by Joel-C-Johnson** [comment]
the current code sent a mail to the admin(role) users. The mail should be sent to the user who requested for admin access (by creating an organisation request) saying that "your organisation request has been approved/disapproved by the super admin
