### ISSUE TITLE
Internal Server error while adding bible books

### ISSUE THREAD

**Issue by jincypjose** [Bridgeconn/vachan-api#158]
API: POST - v2/bibles/{source_name}/books
I gave
 {
    "USFM": "\\id MAT\n\\c 1\n\\p\n\\v 1 इब्राहीम की सन्‍तान, दाऊद की सन्‍तान,यीशु मसीह की वंशावली ।"
  } as input 
In Response i got
500  Error: Internal Server Error
{
  "error": "Error",
  "details": "'en_NIV_1_bible'"
}
the request url was https://api.vachanengine.org/v2/bibles/en_NIV_1_bible/books

**Comment by kavitharaju** [comment]
The issue was with the deployment on the server.
Upon pulling code and building DB again the issue got resolved
