### ISSUE TITLE
API Requirement for tokenUpdation

### ISSUE THREAD

**Issue by Joel-C-Johnson** [Bridgeconn/vachan-api#159]
After Updating the token we need a get API that should send back the updated token translation from the Server. 
Here are the UI details
FrameWork : 
![translationFrameWork](https://user-images.githubusercontent.com/25791348/121488841-17e33680-c9f1-11eb-9c1d-727b0aa4253b.png)

RCL which I made:
![translationRCL](https://user-images.githubusercontent.com/25791348/121489831-19612e80-c9f2-11eb-83eb-f91475e08207.png)

From the UI, Below is the input sent from the UI,

```
 {
        projectId: 100000,
        token: 'સત્યમાં',
        occurrences: [
            {
               sentenceId: 65001004,
               offset: [12, 19],
            } 
         ]
}

```
Expected outPut from the Server,

   ```
 {
        projectId: 100000,
        token: 'સત્યમાં',
        occurrences: [
            {
               sentenceId: 65001004,
               offset: [12, 19],
               translation: 'translation'
           }   
        ]
  }
```

Kindly note that if there are multiple occurrences, sent the translation for that corresponding sentenceid and offset with the above json format..

**Comment by kavitharaju** [comment]
An input like the one below needs to be passed as a body parameter in an API
```
{
        projectId: 100000,
        token: 'સત્યમાં',
        occurrences: [
            {
               sentenceId: 65001004,
               offset: [12, 19],
            } 
         ]
}
```
To use Body parameter we will have to use PUT or POST.
This API is not really making any changes on the server. So a GET method is more appropriate.

So, a way to implement this a GET request would be to as follows
- use query params `project_id`, `token`, `sentence_id` `offset`

This would limit our scope to just one occurence of a token. Would that be okay?

**Comment by Joel-C-Johnson** [comment]
yeah currently this will help to sort the requirement. thank u
