### ISSUE TITLE
API Requirement for books and chapters for a source 

### ISSUE THREAD

**Issue by jincypjose** [Bridgeconn/vachan-api#160]
Can i get list of books and chapters for a source and not verse also, as it will be quite a lot for the whole bible. The api i am using is http://127.0.0.1:8000/v2/bibles/en_KJV_1_bible/books?versification=true&active=true. 
something similar to json given in this https://github.com/Bridgeconn/VachanOnline-v2/blob/master/src/store/bibleData.js link

**Comment by kavitharaju** [comment]
Planning to use a JSON similar to [this](https://github.com/Copenhagen-Alliance/versification-specification/blob/master/versification-mappings/standard-mappings/org.json#L4). This is a recommended standard. Following that would help us scaling better later.

Hope that would work for you, @jincypjose

**Comment by jincypjose** [comment]
Yeah, that would work
