### ISSUE TITLE
List of users: while assigning user to project

### ISSUE THREAD

**Issue by udkumar** [Bridgeconn/vachan-api#363]
As admin on project page I want to assign user to project but I am not able to list of user to select.

Can we add APIs for user list?

**Comment by kavitharaju** [comment]
Users also should have GET and PUT APIs in the same pattern as other contents we have in vachan. These APIs can be implemented such that they call the Kratos APIs from within.

The GET api should be able to filter results based on various available info like roles, active status and also do a partial matching on user-name.

**Comment by kavitharaju** [comment]
In the current implemetation, query parameter `page` is used. Need to change that to `skip` like in other APIs.
