### ISSUE TITLE
Backup database's docker-volume

### ISSUE THREAD

**Issue by kavitharaju** [Bridgeconn/vachan-api#366]
In deployment, Our DBs on the server( vachan-DB and Kratos-DB) are persisted as volumes but not backed-up otherwise.

This looks like a good option to do that https://github.com/offen/docker-volume-backup .

NOTE: Keep an eye on an issue that talks about deprecating some features in their future v3 release.

**Comment by sijumoncy** [comment]
Test Done for Rsync ( Production Server -> Internal Backup Server )

|         Tests                          |      Status                  |
| ---------------------------- | ---------------------- |
| Sync Directory Content     | Ok                            | 
| Add File                             | Ok                            | 
| Update File Content          | Ok                            | 
| Delete                                | Ok                            | 
| Rename                              | Ok                            |
