### ISSUE TITLE
Redis to cache the gloss/token tries

### ISSUE THREAD

**Issue by kavitharaju** [Bridgeconn/vachan-api#392]
Check possibility of using Redis to cache the gloss/token tries. 

Now a trie is created every time a tokenization request is made. This leads to long response time for the tokenization APIs and other APIs that use tokenization internally. If the trie is once made and loaded to cache, this time cam be reduced.

The tries stored in cache also needs to be updated upon addition of new tokens to the translation memory via gloss API or token translation API

**Comment by kavitharaju** [comment]
Need to asses the time difference  and server memory requirements upon bringing in this change.
- Choose 2 or 3 languages with translation memory entries 2000 or more
     - If not already available on server can add gloss entries of token translations available via [add gloss](https://api.vachanengine.org/docs#/Nlp/add_gloss_v2_nlp_learn_gloss_post) API

- Monitor the response time and server resource usage of the following APIs before and after this change.
    - Tokenization APIs
        - [/v2/autographa/project/tokens](https://api.vachanengine.org/docs#/Autographa-Translation/get_tokens_v2_autographa_project_tokens_get) 
        - [/v2/translation/tokens](https://api.vachanengine.org/docs#/Generic%20Translation/tokenize_v2_translation_tokens_put)
    - Suggestion APIs
        - [/v2/autographa/project/suggestions](https://api.vachanengine.org/docs#/Translation%20Suggestion/suggest_auto_translation_v2_autographa_project_suggestions_put)
        - [/v2/translation/suggestions](https://api.vachanengine.org/docs#/Translation%20Suggestion/suggest_translation_v2_translation_suggestions_put)
    - APIs updating the Translation memory
        - [/v2/autographa/project/tokens-apply token translations)](https://api.vachanengine.org/docs#/Autographa-Translation/apply_token_translations_v2_autographa_project_tokens_put)   
        - [/v2/translation/token-translate- token replace](https://api.vachanengine.org/docs#/Generic%20Translation/token_replace_v2_translation_token_translate_put)
        - [/v2/nlp/learn/gloss](https://api.vachanengine.org/docs#/Nlp/add_gloss_v2_nlp_learn_gloss_post)
        - [/v2/nlp/learn/alignment](https://api.vachanengine.org/docs#/Nlp/add_alignments_v2_nlp_learn_alignment_post)

The API calls for testing should be done alternatively for different languages. Also adding a few large media API calls to take up cache space would be good.

Our main concerns behind this
     - Is using cache for storing these large datastructures and media files going to be memory expensive?
     - Is using cache really improving the speed ?
     - If too many swaps happen for items in cache, is it going to cost response time?

**Comment by sijumoncy** [comment]
Test For Tries Done

- Storing these large datastructures in memory not going to be expensive. ( Hi token try : 3000 tokens , cache size 80kb)
- Both writing in Db and tries are not an overhead process
- response time in reading is less
- updating and reading of cache is not much big task , also improves response time than without cache

Details of trie test : https://bridgeconn-my.sharepoint.com/:x:/p/siju_moncy/EW2oWGfADupKofy_nGpjwkABPET4-qYXMUg7FjfbGEuY4w?e=7t6cye
