### ISSUE TITLE
Getting spaces as token after suggestion API

### ISSUE THREAD

**Issue by ashish-garg-25** [Bridgeconn/vachan-api#395]
Suggestion API is making seperate token for space.

**Comment by kavitharaju** [comment]
We are not cleaning up spaces in the original source text inorder to preserve all the information there. So even when splitting tokens we would preserve the spaces in between them. 

If the client application wants to handle spaces differently, it can choose to handle it at UI side, like not to display space only tokens. But make sure the indices will not get altered incorrectly by doing so
