### ISSUE TITLE
server crashing while making suggestion  API call

### ISSUE THREAD

**Issue by LijuJacob08** [Bridgeconn/vachan-api#398]
Hi Kavitha,

1 facing this issue while opening the Project page which is initiating the suggestion API . 

----------------------------------------------
Observations
- Project opens for the book size is small(like having 1 chapter with few verse) in a minute or two. 
- noted that suggestion api is being called twice

following are the request details:-

1)Request Header

    1. :authority: 
       api.vachanengine.org
    2. :method: 
       PUT
    3. :path: 
       /v2/autographa/project/suggestions?project_id=100016
    4. :scheme: 
       https
    5. accept: 
       */*
    6. accept-encoding: 
       gzip, deflate, br
    7. accept-language: 
       en-US,en;q=0.9
    8. app: 
       Autographa
    9. authorization: 
       Bearer zLLme29wyO8uRr8nHSAblDIoyNCIo2Z3
    10. content-length: 
       0
    11. origin: 
       http://localhost:3000
    12. referer: 
       http://localhost:3000/
    13. sec-ch-ua: 
       " Not A;Brand";v="99", "Chromium";v="100", "Google Chrome";v="100"
    14. sec-ch-ua-mobile: 
       ?0
    15. sec-ch-ua-platform: 
       "Linux"
    16. sec-fetch-dest: 
       empty
    17. sec-fetch-mode: 
       cors
    18. sec-fetch-site: 
       cross-site
    19. user-agent: 
       Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36

2)Payload
![image](https://user-images.githubusercontent.com/93033055/178917640-ca95f2e1-f163-4b47-8927-18f6e55cc86e.png)

3)suggestion was called thrice(3=1 options +2 PUT calls)

![image](https://user-images.githubusercontent.com/93033055/178917728-3d746119-242d-4239-9da4-56a338e2b59e.png)

4)after some time got 

![image](https://user-images.githubusercontent.com/93033055/178917757-2a549b1c-f30f-4757-8e97-eb7ba88ca903.png)
-----------------------------------------------------------------------------------

**Comment by kavitharaju** [comment]
Why is the same API called thrice?

Also, are you not using query params like `sentence_id_list` or `sentence_id_range`? This specifies the verses you are trying to load now. If not specified, the suggestion generation will be performed on all available verses in the project, which will be resource intense.

Will look into why this issues is happening and will attempt to tackle the time delay of APIs response. Some things I will be attempting
* Use caching(Redis) of trie data structure used for suggestions and tokenization
* Convert this API to a backgroud job. It will then return a job id and UI will have to check server if the job is completed to get the response.

**Comment by kavitharaju** [comment]
The UI code update to use verse ranges to run the suggestions only on selected verses and not on the  entire project content, as well as, ensuring the API is called only once upon each page load had resolved the issue.

Along with that we have also implemented the caching of tries at the backend.
