### ISSUE TITLE
Words are getting split in  suggestions and/or tokenization APIs

### ISSUE THREAD

**Issue by kavitharaju** [Bridgeconn/vachan-api#404]
After add `a` as a token to the system, later it is giving suggested tokenzations like this
`P`   `a`  `ul`.

There could be  a flag on the tokenization and suggestion APIs saying words are not to be split!

**Comment by kavitharaju** [comment]
Ashish, could you please share here the response object you get for the verse with this issue?

I am not able to replicate the same issue. I would like to take a look at the `DraftMeta` of the response you are getting.

**Comment by ashish-garg-25** [comment]
`[
    {
        "sentenceId": 57001001,
        "surrogateId": "tit 1:1",
        "sentence": "Greetings from Paul, a servant belonging to God and an apostle sent out by Jesus Christ. My work is to help God’s chosen people trust him more and understand the true teaching about Jesus. This teaching will lead them to live in a way that honours and pleases God.",
        "draft": "greet greet from Translation Paul, a translation new translation belong w g o apostletranslation sent  by jesustranslation christ. i work work is world people you all help help g’s select select select select people trust god more o understand world people you all truth encourage encourage about jesustranslation. this encourage encourage will lead they world people you all kive  a way that obey o happy happy g.",
        "draftMeta": [
            [
                [
                    0,
                    9
                ],
                [
                    0,
                    11
                ],
                "confirmed"
            ],
            [
                [
                    9,
                    10
                ],
                [
                    11,
                    12
                ],
                "untranslated"
            ],
            [
                [
                    10,
                    14
                ],
                [
                    12,
                    28
                ],
                "confirmed"
            ],
            [
                [
                    14,
                    15
                ],
                [
                    28,
                    29
                ],
                "untranslated"
            ],
            [
                [
                    15,
                    16
                ],
                [
                    29,
                    30
                ],
                "untranslated"
            ],
            [
                [
                    16,
                    17
                ],
                [
                    30,
                    31
                ],
                "confirmed"
            ],
            [
                [
                    17,
                    19
                ],
                [
                    31,
                    33
                ],
                "untranslated"
            ],
            [
                [
                    19,
                    21
                ],
                [
                    33,
                    35
                ],
                "untranslated"
            ],
            [
                [
                    21,
                    23
                ],
                [
                    35,
                    49
                ],
                "confirmed"
            ],
            [
                [
                    23,
                    30
                ],
                [
                    49,
                    64
                ],
                "confirmed"
            ],
            [
                [
                    30,
                    31
                ],
                [
                    64,
                    65
                ],
                "untranslated"
            ],
            [
                [
                    31,
                    40
                ],
                [
                    65,
                    71
                ],
                "confirmed"
            ],
            [
                [
                    40,
                    41
                ],
                [
                    71,
                    72
                ],
                "untranslated"
            ],
            [
                [
                    41,
                    43
                ],
                [
                    72,
                    73
                ],
                "confirmed"
            ],
            [
                [
                    43,
                    44
                ],
                [
                    73,
                    74
                ],
                "untranslated"
            ],
            [
                [
                    44,
                    47
                ],
                [
                    74,
                    75
                ],
                "confirmed"
            ],
            [
                [
                    47,
                    48
                ],
                [
                    75,
                    76
                ],
                "untranslated"
            ],
            [
                [
                    48,
                    51
                ],
                [
                    76,
                    77
                ],
                "confirmed"
            ],
            [
                [
                    51,
                    52
                ],
                [
                    77,
                    78
                ],
                "untranslated"
            ],
            [
                [
                    52,
                    62
                ],
                [
                    78,
                    96
                ],
                "confirmed"
            ],
            [
                [
                    62,
                    63
                ],
                [
                    96,
                    97
                ],
                "untranslated"
            ],
            [
                [
                    63,
                    71
                ],
                [
                    97,
                    102
                ],
                "confirmed"
            ],
            [
                [
                    71,
                    72
                ],
                [
                    102,
                    103
                ],
                "untranslated"
            ],
            [
                [
                    72,
                    74
                ],
                [
                    103,
                    105
                ],
                "untranslated"
            ],
            [
                [
                    74,
                    75
                ],
                [
                    105,
                    106
                ],
                "untranslated"
            ],
            [
                [
                    75,
                    80
                ],
                [
                    106,
                    122
                ],
                "suggestion"
            ],
            [
                [
                    80,
                    81
                ],
                [
                    122,
                    123
                ],
                "untranslated"
            ],
            [
                [
                    81,
                    87
                ],
                [
                    123,
                    129
                ],
                "suggestion"
            ],
            [
                [
                    87,
                    89
                ],
                [
                    129,
                    131
                ],
                "untranslated"
            ],
            [
                [
                    89,
                    91
                ],
                [
                    131,
                    132
                ],
                "confirmed"
            ],
            [
                [
                    91,
                    92
                ],
                [
                    132,
                    133
                ],
                "untranslated"
            ],
            [
                [
                    92,
                    96
                ],
                [
                    133,
                    142
                ],
                "confirmed"
            ],
            [
                [
                    96,
                    97
                ],
                [
                    142,
                    143
                ],
                "untranslated"
            ],
            [
                [
                    97,
                    99
                ],
                [
                    143,
                    145
                ],
                "suggestion"
            ],
            [
                [
                    99,
                    100
                ],
                [
                    145,
                    146
                ],
                "untranslated"
            ],
            [
                [
                    100,
                    102
                ],
                [
                    146,
                    166
                ],
                "confirmed"
            ],
            [
                [
                    102,
                    103
                ],
                [
                    166,
                    167
                ],
                "untranslated"
            ],
            [
                [
                    103,
                    107
                ],
                [
                    167,
                    176
                ],
                "confirmed"
            ],
            [
                [
                    107,
                    108
                ],
                [
                    176,
                    177
                ],
                "untranslated"
            ],
            [
                [
                    108,
                    111
                ],
                [
                    177,
                    178
                ],
                "confirmed"
            ],
            [
                [
                    111,
                    112
                ],
                [
                    178,
                    179
                ],
                "untranslated"
            ],
            [
                [
                    112,
                    113
                ],
                [
                    179,
                    180
                ],
                "untranslated"
            ],
            [
                [
                    113,
                    114
                ],
                [
                    180,
                    181
                ],
                "untranslated"
            ],
            [
                [
                    114,
                    120
                ],
                [
                    181,
                    208
                ],
                "confirmed"
            ],
            [
                [
                    120,
                    121
                ],
                [
                    208,
                    209
                ],
                "untranslated"
            ],
            [
                [
                    121,
                    127
                ],
                [
                    209,
                    215
                ],
                "confirmed"
            ],
            [
                [
                    127,
                    128
                ],
                [
                    215,
                    216
                ],
                "untranslated"
            ],
            [
                [
                    128,
                    133
                ],
                [
                    216,
                    221
                ],
                "confirmed"
            ],
            [
                [
                    133,
                    134
                ],
                [
                    221,
                    222
                ],
                "untranslated"
            ],
            [
                [
                    134,
                    137
                ],
                [
                    222,
                    225
                ],
                "confirmed"
            ],
            [
                [
                    137,
                    138
                ],
                [
                    225,
                    226
                ],
                "untranslated"
            ],
            [
                [
                    138,
                    142
                ],
                [
                    226,
                    230
                ],
                "confirmed"
            ],
            [
                [
                    142,
                    143
                ],
                [
                    230,
                    231
                ],
                "untranslated"
            ],
            [
                [
                    143,
                    146
                ],
                [
                    231,
                    232
                ],
                "confirmed"
            ],
            [
                [
                    146,
                    147
                ],
                [
                    232,
                    233
                ],
                "untranslated"
            ],
            [
                [
                    147,
                    157
                ],
                [
                    233,
                    243
                ],
                "confirmed"
            ],
            [
                [
                    157,
                    158
                ],
                [
                    243,
                    244
                ],
                "untranslated"
            ],
            [
                [
                    158,
                    161
                ],
                [
                    244,
                    264
                ],
                "confirmed"
            ],
            [
                [
                    161,
                    162
                ],
                [
                    264,
                    265
                ],
                "untranslated"
            ],
            [
                [
                    162,
                    166
                ],
                [
                    265,
                    270
                ],
                "confirmed"
            ],
            [
                [
                    166,
                    167
                ],
                [
                    270,
                    271
                ],
                "untranslated"
            ],
            [
                [
                    167,
                    175
                ],
                [
                    271,
                    290
                ],
                "confirmed"
            ],
            [
                [
                    175,
                    176
                ],
                [
                    290,
                    291
                ],
                "untranslated"
            ],
            [
                [
                    176,
                    181
                ],
                [
                    291,
                    296
                ],
                "confirmed"
            ],
            [
                [
                    181,
                    182
                ],
                [
                    296,
                    297
                ],
                "untranslated"
            ],
            [
                [
                    182,
                    187
                ],
                [
                    297,
                    313
                ],
                "confirmed"
            ],
            [
                [
                    187,
                    189
                ],
                [
                    313,
                    315
                ],
                "untranslated"
            ],
            [
                [
                    189,
                    193
                ],
                [
                    315,
                    319
                ],
                "confirmed"
            ],
            [
                [
                    193,
                    194
                ],
                [
                    319,
                    320
                ],
                "untranslated"
            ],
            [
                [
                    194,
                    202
                ],
                [
                    320,
                    339
                ],
                "confirmed"
            ],
            [
                [
                    202,
                    203
                ],
                [
                    339,
                    340
                ],
                "untranslated"
            ],
            [
                [
                    203,
                    207
                ],
                [
                    340,
                    344
                ],
                "untranslated"
            ],
            [
                [
                    207,
                    208
                ],
                [
                    344,
                    345
                ],
                "untranslated"
            ],
            [
                [
                    208,
                    212
                ],
                [
                    345,
                    349
                ],
                "confirmed"
            ],
            [
                [
                    212,
                    213
                ],
                [
                    349,
                    350
                ],
                "untranslated"
            ],
            [
                [
                    213,
                    217
                ],
                [
                    350,
                    354
                ],
                "confirmed"
            ],
            [
                [
                    217,
                    218
                ],
                [
                    354,
                    355
                ],
                "untranslated"
            ],
            [
                [
                    218,
                    220
                ],
                [
                    355,
                    375
                ],
                "confirmed"
            ],
            [
                [
                    220,
                    221
                ],
                [
                    375,
                    376
                ],
                "untranslated"
            ],
            [
                [
                    221,
                    228
                ],
                [
                    376,
                    381
                ],
                "confirmed"
            ],
            [
                [
                    228,
                    229
                ],
                [
                    381,
                    382
                ],
                "untranslated"
            ],
            [
                [
                    229,
                    230
                ],
                [
                    382,
                    383
                ],
                "confirmed"
            ],
            [
                [
                    230,
                    231
                ],
                [
                    383,
                    384
                ],
                "untranslated"
            ],
            [
                [
                    231,
                    234
                ],
                [
                    384,
                    387
                ],
                "untranslated"
            ],
            [
                [
                    234,
                    235
                ],
                [
                    387,
                    388
                ],
                "untranslated"
            ],
            [
                [
                    235,
                    239
                ],
                [
                    388,
                    392
                ],
                "untranslated"
            ],
            [
                [
                    239,
                    240
                ],
                [
                    392,
                    393
                ],
                "untranslated"
            ],
            [
                [
                    240,
                    247
                ],
                [
                    393,
                    397
                ],
                "confirmed"
            ],
            [
                [
                    247,
                    248
                ],
                [
                    397,
                    398
                ],
                "untranslated"
            ],
            [
                [
                    248,
                    251
                ],
                [
                    398,
                    399
                ],
                "confirmed"
            ],
            [
                [
                    251,
                    252
                ],
                [
                    399,
                    400
                ],
                "untranslated"
            ],
            [
                [
                    252,
                    259
                ],
                [
                    400,
                    411
                ],
                "confirmed"
            ],
            [
                [
                    259,
                    260
                ],
                [
                    411,
                    412
                ],
                "untranslated"
            ],
            [
                [
                    260,
                    263
                ],
                [
                    412,
                    413
                ],
                "confirmed"
            ],
            [
                [
                    263,
                    264
                ],
                [
                    413,
                    414
                ],
                "untranslated"
            ]
        ]
    }
]`

Please refer this @kavitharaju

**Comment by kavitharaju** [comment]
Here I think Paul is not getting split. Can you point me to an index where the same issue is occurring?

**Comment by ashish-garg-25** [comment]
[
                [
                    14,
                    15
                ],
                [
                    28,
                    29
                ],
                "untranslated"
            ],
            [
                [
                    15,
                    16
                ],
                [
                    29,
                    30
                ],
                "untranslated"
            ],
            [
                [
                    16,
                    17
                ],
                [
                    30,
                    31
                ],
                "confirmed"
            ],
            [
                [
                    17,
                    19
                ],
                [
                    31,
                    33
                ],
                "untranslated"
            ],


These index are referring to paul @kavitharaju

**Comment by kavitharaju** [comment]
```
[
[16,17],
[30,31],
"confirmed"
]
```
This refers to `a` right? As it shows here,  it is "confirmed" translation, meaning user done, not "suggested" by system. 
I don't see this issue of word being split by system in suggestion when I try with other sentences having `a` in them. So I think this particular case might have happened from user end (our end during development). We might have passed in the specific index of that "a", that come with "Paul" and applied a translation to it, instead of the indices of a different word "a". 

@ashish-garg-25 , If you think this is not the case and the system is actually splitting whole words and giving them as suggestions, please let me know. And share some examples where I can re-generate the behavior on the deployed app.

**Comment by ashish-garg-25** [comment]
I don't find any other example like this possibly we have mistakenly apply translation to token 'a' while developing application.
Will let you know if i found other example. @kavitharaju

**Comment by kavitharaju** [comment]
Okay. Lets close this issue then.
Can re-open in case we find it again.

@JesniJ 
Just letting you know of this issue. Please test this case while you do the next round of QA
> if a particular word, say "cat", is present two times in a text like `The cat and another cat sat to eat.` and the user applies a translation for the second cat and not the first. Next time the same sentence is loaded it should show first cat as "untranslated" and second as "confirmed" correctly
