### ISSUE TITLE
Use calender versioning

### ISSUE THREAD

**Issue by kavitharaju** [Bridgeconn/vachan-api#415]
For sources we release on gitlab, version should be specified by date of release : ShortYear.ShortMonth.ShortDay e.g. 22.9.7.
https://calver.org/

Make required changes on Vachan-api to ensure the sorting, validation, DB data-types used are all are updated to support this.
 
Also make a plan to accommodate other versioning-schemes for adding sources that are released elsewhere.

**Comment by kavitharaju** [comment]
These might help in implementing sorting and maybe in supporting different schemes
```
>>> from distutils.version import LooseVersion
>>> versions = ["1.7.0", "1.7.0.rc0", "1.8.0"]
>>> lv = [LooseVersion(v) for v in versions]
>>> sorted(lv, reverse=True)
[LooseVersion ('1.8.0'), LooseVersion ('1.7.0.rc0'), LooseVersion ('1.7.0')]
```

or 

```
from distutils.version import StrictVersion
versions = ["1.1.2", "1.0.0", "1.3.3", "1.0.12", "1.0.2"]
versions.sort(key=StrictVersion)
```

**Comment by kavitharaju** [comment]
https://stackoverflow.com/questions/59247203/best-way-to-store-versions-in-postgresql this discussion and options mentioned there are worth considering

**Comment by kavitharaju** [comment]
Again noting down for consideration/discussion. Do we need to change our terminologies related to versions in DB

We call "King James Version"  or "Indian Revisied version", `version`
and correspondingly "KJV" and "IRV" `version_code`.
The numbers associated with them, `5` in IRV5 are called `revisions`, and we have been using intergers to represent them.

I feel that this use of terminology is not quite what comes to mind when we hear the term "version", by which we usually mean a "number like version" say `2.0` or `22.9.12`. But on the other hand our usage might be more tied to the Biblical domain.

Do we need to consider a revision of these terminologies? 

May be call "King James Version"  `name`, "KJV" `short_name` and the `KJV_2_en_Bible`, which we use are a unique value to identify the source item internally, a `long_name` or `unique_name`. Then use the word `version` to denote what we call revision now .

Any thoughts? @joelthe1 @rinsingh

**Comment by joelthe1** [comment]
As you suspected, 'version` means something different in the BT world. e.g. 'King James Version' itself is the name of the version and, as is the case here, a lot of the times literally includes the term 'version' in it.

For our DB schema, I think it may be more appropriate to call `version_name`='King James Version' and `version_short_name`='KJV' and `version_tag`='22.9.7' (borrowing from git tag) and `version_id`='KJV_2_en_Bible' (which I assume would be a concatenation that includes `version_short_name`, language code, etc.)

Also, I just looked into `distutils` and it says that it is deprecated. I think we should somehow attempt to save the `published_date` and probably another flag that denotes if a specific `version_tag` is the default in the DB.

**Comment by kavitharaju** [comment]
At present we have a field, "year". Its not the exact date of publishing though. 

**Pros of using Year**: It might serve as an approximation when exact date of release of external resources are not known. And simpler to handle(passing over the object b/w pydantic, python, postgres) as it is just integer.

**Cons of using year**: If there are multiple releases in a year and the version tag is unknown, then determining the latest is ambiguous.
