### ISSUE TITLE
Kratos Version change

### ISSUE THREAD

**Issue by sijumoncy** [Bridgeconn/vachan-api#429]
upgrade kratos to new version v0.10.1

**Comment by kavitharaju** [comment]
Need to look into the issue happened upon updating the Kratos version on staging server.

First the vachan-api contaier was not starting successfully, upon code update after auto deployment.
Upon restarting the Kratos DB(that is run separately, with database.yml) miragte started to run for a long time, as if creating new DB, and ended in error saying the roles are not existing in DB

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/18255929/193742209-40742c17-2c8c-4aa7-bd25-4b439ca8aba3.png)

Then, after the code changes were reverted, it was found that, the DB got created fresh(with older Kratos version), thus loosing all the user data we had.

Need to look into this matter, by testing it locally and ensuring that 
- Kratos version update does not make old DB incompatible and also 
- will not re-create the DB , if an older one exists.

**Comment by kavitharaju** [comment]
https://github.com/ory/kratos/releases/tag/v1.0.0
