### ISSUE TITLE
New API for draft update

### ISSUE THREAD

**Issue by kavitharaju** [Bridgeconn/vachan-api#441]
In the translation project, token translations are being applied for specific tokens. This makes an alignment between the source text phrases and corresponding target phrases/words. This way of draft updation is feasible only when the assumption, that every word in both translations would be able to align with each other, holds. This may not be the case always.

Depending on the nature of the translation project there might be words that user may want to keep un-aligned to source text but are necessary to be included in the target translation. Example functional words like in , of, is etc. This kind of usecase is coming up in sign language translation. Signs like "Call" "I", reference to the subject of the conversation etc comes in sign sequence that may not be alignable to source text.

To be able to submit these kind of words also to server we need a different API. I suggest a draft update API, that would provide the whole updated draft sentence and draft_metadata indicating which all words have alignments with each other.
PUT /v2/autographa/project/draft similar to the GET draft we have now [/v2/autographa/project/draft](https://api.vachanengine.org/docs#/Autographa-Translation/get_draft_v2_autographa_project_draft_get)
Example payload.
```
{
"sentenceId": 10001,
"sentence": "A B C D ",
"draft": " x y a b d x y c ",
"draft_metadata": [[A, a], [B, b], [C, c], [D, d]]
}
```
The payload wont be exaclty like this. draft_metadata will need indices of aligned words and information of whether its confirmed/untranslated etc. Given so, for ease of understanding and dicsussion.

**Comment by joelthe1** [comment]
One possible alignment format we could use is the pharoah format which supports m-to-m mapping between tokens. e.g. [here](https://github.com/clab/fast_align#output).

**Comment by kavitharaju** [comment]
We already have an alignment format we use, which is similar to the Pharoah's. But we specify the start and end index of each word/phrase/morpheme instead of the word count. All out internal logic is based on this alignment format. 
This gives us a lot of flexibility in term of representing different cases of alignments.
```
[   {     
     "sentenceId": 0,
     "surrogateId": "string", 
     "sentence": "Abraham's son is Issac", 
     "draft": "അബ്രഹാമിന്റെ son is Issac",
     "draftMeta": [ [ [0, 9 ], [0,12],"confirmed"],
                           [[9,22],[12,25],"untranslated"]
                         ]   
} ]
```

In this issue, we are discussing an API that allows the UI App to write this field and the drafts field directly. Which would require the UI app also to work with the same format(Which they already are, because that is the response they get now), and give them more flexibility in term of representing different cases of alignments, including the words that are not aligned.
