### ISSUE TITLE
Need to distinguish translation projects based on Apps

### ISSUE THREAD

**Issue by kavitharaju** [Bridgeconn/vachan-api#442]
Now there is only one translation project working using our translation APIs. That is the sign project. But later if new apps come then we have a need to distinguish which project belongs to which app, also specify if there are projects that are sharable across apps.

For instance the sign app works with its own specific logic that each target word(token) of the translatio would a valid sign token with its dictionary entry. If this app shows a text project in its list of projects and tries to display its contents via the sign UI, it will never work. So there should a way to say only sign project are to loaded on sign app. For that we need to keep the record of which app created which project, even if the rest of translation logic are shareable.

I suggest either a new column in the translation projects table or if we don't want to change APIs and DB schema, a field in project metadata.

**Comment by joelthe1** [comment]
I think having a field, say `compatible_with`, that is a list of strings that name the apps (based on some standard app names in the DB) might be enough.
