### ISSUE TITLE
Extra space at 0 index in draft meta

### ISSUE THREAD

**Issue by ashish-garg-25** [Bridgeconn/vachan-api#485]
While fetching the second verse of the book Titus. I am getting extra space in draft and draftMeta attaching a screenshot(Network request) of the same
<img width="305" alt="image" src="https://user-images.githubusercontent.com/100211072/213918674-9d0ecd8a-c8d8-4b56-a020-4be951b1b633.png">
@kavitharaju

**Comment by kavitharaju** [comment]
@ashish-garg-25 , I am unable to replicate the behaviour with same input sentence.
![image](https://user-images.githubusercontent.com/18255929/213999985-6e74b7c7-f40a-46b6-b5d1-bc9796470db4.png)
 
And it sounds peculiar to me that it happens only in second verse. For backend it doesn't have a context of whether its the first or second verse. All sentences are treated as independant requests. So I request you to double check from UI if there has been submissions to server that cause this behaviour. As you can see the suggestion I got dosn'e include the first two words in your output.

After checking front-end once more if you still think its issue from back end please share the project id too

**Comment by kavitharaju** [comment]
I am able to replicate the issue now. It happens at the second time we run suggestions on the same verse. Will fix.
@ashish-garg-25

**Comment by AnnCherianA** [comment]
Hi Kavitha,

This issue raised by Jesni may

 be similar .

https://gitlab.bridgeconn.com/software/research/sign-language/sign-translation-assistant/-/issues/86






Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kavitharaju** [comment]
Yes Ann, It should be the corresponding issue in UI project. This fix will be incorporated in the UI and status will be updated there too.
