### ISSUE TITLE
GET dictionary api with total row count

### ISSUE THREAD

**Issue by LijuJacob08** [Bridgeconn/vachan-api#490]
Requirement:-
in our cuurent Current api https://stagingapi.vachanengine.org/docs#/Dictionaries/get_dictionary_word_v2_dictionaries__source_name__get
need one additional change-
need to see one more key to he existing json- which is total no. of rows.

**Comment by kavitharaju** [comment]
The response of that API is an array. It will break the structure and common pattern we follow in similar APIs if we add the count to that response object. 
How about a new API for just this purpose, to get the count of all words in a specific dictionary? There we can give you more flexibility to count active and inactive words the way you need.

**Comment by LijuJacob08** [comment]
new API for just this purpose is a good idea.
 
just to make sure is there any possiblity to count with the new word count api : 
- total active  
- total inactive
- total  active + inactive words in total word count[ currently what I can see is that ,we can either see the total active words or the inactive words, please correct me if i had assumed it wrong]

other than this i had tried the new word count  api  and the below combinaion in existing GET API 
("https://stagingapi.vachanengine.org/v2/dictionaries/ins_IRV_1_dictionary?exact_match=false&word_list_only=true&active=true&skip=0&limit=99999")
both outputs are different.
here-> https://stagingapi.vachanengine.org/docs#/Dictionaries/get_dictionary_word_count_v2_dictionaries__source_name__count_get
 is returning the value 100 ,though total no. active word count is much more than 100,  looks to me like the api  is still having the back logic of default limit as 100.

**Comment by kavitharaju** [comment]
@LijuJacob08 
> is there any possiblity to count with the new word count api :
    total active
    total inactive
    total active + inactive words in total word count[ currently what I can see is that ,we can either see the total active words or the inactive words, please correct me if i had assumed it wrong]

As per the new API, [/v2/dictionaries/{source_name}/count](https://stagingapi.vachanengine.org/docs#/Dictionaries/get_dictionary_word_count_v2_dictionaries__source_name__count_get)

* for total active count , https://stagingapi.vachanengine.org/v2/dictionaries/ins_IRV_1_dictionary/count?active=true
* for total deactivated, https://stagingapi.vachanengine.org/v2/dictionaries/ins_IRV_1_dictionary/count?active=false
* for count of both, https://stagingapi.vachanengine.org/v2/dictionaries/ins_IRV_1_dictionary/count

The skip and limit value got applied by default. Will be fixing that soon.
