### ISSUE TITLE
When removing word from draft next word is draft is showing incorrect

### ISSUE THREAD

**Issue by ashish-garg-25** [Bridgeconn/vachan-api#501]
After performing delete action on a draft and pushing it to DB. In new PUT suggestion call next draft indices are coming wrong
@kavitharaju

**Comment by kavitharaju** [comment]
@ashish-garg-25 Can you please provide the payload you are pushing to DB and the response you are getting on subsequent suggestion call, for a verse?

**Comment by ashish-garg-25** [comment]
@kavitharaju 

**First API call to fetch data**
[{"sentenceId":41001003,"surrogateId":"mat 1:3","sentence":"And Judas begat Phares and Zara of Thamar; and Phares begat Esrom; and Esrom begat Aram;","draft":"a a me a a","draftMeta":[[[0,3],[0,1],"suggestion"],[[3,4],[1,1],"untranslated"],[[4,9],[1,1],"untranslated"],[[9,10],[1,1],"untranslated"],[[10,15],[1,1],"untranslated"],[[15,16],[1,1],"untranslated"],[[16,22],[1,1],"untranslated"],[[22,23],[1,1],"untranslated"],[[23,23],[1,2],"untranslated"],[[23,26],[2,3],"suggestion"],[[26,27],[3,3],"untranslated"],[[27,31],[3,3],"untranslated"],[[31,32],[3,3],"untranslated"],[[32,32],[3,4],"untranslated"],[[32,34],[4,6],"suggestion"],[[34,35],[6,6],"untranslated"],[[35,41],[6,6],"untranslated"],[[41,43],[6,6],"untranslated"],[[43,43],[6,7],"untranslated"],[[43,46],[7,8],"suggestion"],[[46,47],[8,8],"untranslated"],[[47,53],[8,8],"untranslated"],[[53,54],[8,8],"untranslated"],[[54,59],[8,8],"untranslated"],[[59,60],[8,8],"untranslated"],[[60,65],[8,8],"untranslated"],[[65,67],[8,8],"untranslated"],[[67,67],[8,9],"untranslated"],[[67,70],[9,10],"suggestion"],[[70,71],[10,10],"untranslated"],[[71,76],[10,10],"untranslated"],[[76,77],[10,10],"untranslated"],[[77,82],[10,10],"untranslated"],[[82,83],[10,10],"untranslated"],[[83,87],[10,10],"untranslated"],[[87,88],[10,10],"untranslated"]]}]

**Second Pushing new draftMeta to DB**
[
    {
        "draft": "a a me a",
        "draftMeta": [
            [
                [
                    0,
                    3
                ],
                [
                    0,
                    1
                ],
                "suggestion"
            ],
            [
                [
                    3,
                    4
                ],
                [
                    1,
                    1
                ],
                "untranslated"
            ],
            [
                [
                    4,
                    9
                ],
                [
                    1,
                    1
                ],
                "untranslated"
            ],
            [
                [
                    9,
                    10
                ],
                [
                    1,
                    1
                ],
                "untranslated"
            ],
            [
                [
                    10,
                    15
                ],
                [
                    1,
                    1
                ],
                "untranslated"
            ],
            [
                [
                    15,
                    16
                ],
                [
                    1,
                    1
                ],
                "untranslated"
            ],
            [
                [
                    16,
                    22
                ],
                [
                    1,
                    1
                ],
                "untranslated"
            ],
            [
                [
                    22,
                    23
                ],
                [
                    1,
                    1
                ],
                "untranslated"
            ],
            [
                [
                    23,
                    23
                ],
                [
                    1,
                    2
                ],
                "untranslated"
            ],
            [
                [
                    23,
                    26
                ],
                [
                    2,
                    3
                ],
                "suggestion"
            ],
            [
                [
                    26,
                    27
                ],
                [
                    3,
                    3
                ],
                "untranslated"
            ],
            [
                [
                    27,
                    31
                ],
                [
                    3,
                    3
                ],
                "untranslated"
            ],
            [
                [
                    31,
                    32
                ],
                [
                    3,
                    3
                ],
                "untranslated"
            ],
            [
                [
                    32,
                    32
                ],
                [
                    3,
                    4
                ],
                "untranslated"
            ],
            [
                [
                    32,
                    34
                ],
                [
                    4,
                    6
                ],
                "suggestion"
            ],
            [
                [
                    34,
                    35
                ],
                [
                    6,
                    6
                ],
                "untranslated"
            ],
            [
                [
                    35,
                    41
                ],
                [
                    6,
                    6
                ],
                "untranslated"
            ],
            [
                [
                    41,
                    43
                ],
                [
                    6,
                    6
                ],
                "untranslated"
            ],
            [
                [
                    43,
                    43
                ],
                [
                    6,
                    7
                ],
                "untranslated"
            ],
            [
                [
                    43,
                    46
                ],
                [
                    7,
                    7
                ],
                "untranslated"
            ],
            [
                [
                    46,
                    47
                ],
                [
                    6,
                    6
                ],
                "untranslated"
            ],
            [
                [
                    47,
                    53
                ],
                [
                    6,
                    6
                ],
                "untranslated"
            ],
            [
                [
                    53,
                    54
                ],
                [
                    6,
                    6
                ],
                "untranslated"
            ],
            [
                [
                    54,
                    59
                ],
                [
                    6,
                    6
                ],
                "untranslated"
            ],
            [
                [
                    59,
                    60
                ],
                [
                    6,
                    6
                ],
                "untranslated"
            ],
            [
                [
                    60,
                    65
                ],
                [
                    6,
                    6
                ],
                "untranslated"
            ],
            [
                [
                    65,
                    67
                ],
                [
                    6,
                    6
                ],
                "untranslated"
            ],
            [
                [
                    67,
                    67
                ],
                [
                    6,
                    7
                ],
                "untranslated"
            ],
            [
                [
                    67,
                    70
                ],
                [
                    7,
                    8
                ],
                "suggestion"
            ],
            [
                [
                    70,
                    71
                ],
                [
                    8,
                    8
                ],
                "untranslated"
            ],
            [
                [
                    71,
                    76
                ],
                [
                    8,
                    8
                ],
                "untranslated"
            ],
            [
                [
                    76,
                    77
                ],
                [
                    8,
                    8
                ],
                "untranslated"
            ],
            [
                [
                    77,
                    82
                ],
                [
                    8,
                    8
                ],
                "untranslated"
            ],
            [
                [
                    82,
                    83
                ],
                [
                    8,
                    8
                ],
                "untranslated"
            ],
            [
                [
                    83,
                    87
                ],
                [
                    8,
                    8
                ],
                "untranslated"
            ],
            [
                [
                    87,
                    88
                ],
                [
                    8,
                    8
                ],
                "untranslated"
            ]
        ],
        "sentenceId": 41001003
    }
]


**Third fetching new draftMeta from DB**
[{"sentenceId":41001003,"surrogateId":"mat 1:3","sentence":"And Judas begat Phares and Zara of Thamar; and Phares begat Esrom; and Esrom begat Aram;","draft":"a a me  a a","draftMeta":[[[0,3],[0,1],"suggestion"],[[3,4],[1,1],"untranslated"],[[4,9],[1,1],"untranslated"],[[9,10],[1,1],"untranslated"],[[10,15],[1,1],"untranslated"],[[15,16],[1,1],"untranslated"],[[16,22],[1,1],"untranslated"],[[22,23],[1,1],"untranslated"],[[23,23],[1,2],"untranslated"],[[23,26],[2,3],"suggestion"],[[26,27],[3,3],"untranslated"],[[27,31],[3,3],"untranslated"],[[31,32],[3,3],"untranslated"],[[32,32],[3,4],"untranslated"],[[32,34],[4,6],"suggestion"],[[34,35],[6,6],"untranslated"],[[35,41],[6,6],"untranslated"],[[41,43],[6,6],"untranslated"],[[46,47],[6,6],"untranslated"],[[47,53],[6,6],"untranslated"],[[53,54],[6,6],"untranslated"],[[54,59],[6,6],"untranslated"],[[59,60],[6,6],"untranslated"],[[60,65],[6,6],"untranslated"],[[65,67],[6,6],"untranslated"],[[43,43],[6,7],"untranslated"],[[67,67],[7,8],"untranslated"],[[43,46],[8,9],"suggestion"],[[67,67],[9,10],"untranslated"],[[67,70],[10,11],"suggestion"],[[70,71],[11,11],"untranslated"],[[71,76],[11,11],"untranslated"],[[76,77],[11,11],"untranslated"],[[77,82],[11,11],"untranslated"],[[82,83],[11,11],"untranslated"],[[83,87],[11,11],"untranslated"],[[87,88],[11,11],"untranslated"]]}]

**Comment by kavitharaju** [comment]
@ashish-garg-25 

I have looked into the issue. I found that upon fixing two indices in your payload after delete, the `draftMeta` will be correct. And then the subsequent suggestion call also works as expected. 

This is the `draftMeta` you are passing to server after the delete operation
```
    {
      "sentenceId": "41001003",
      "surrogateId": "MAT 1:3",
      "sentence": "And Judas begat Phares and Zara of Thamar; and Phares begat Esrom; and Esrom begat Aram;",
      "draft": "a a me a",
      "draftMeta":[
        [[0,3],[0,1],"suggestion"], # and
        [[3,4],[1,1],"untranslated"], [[4,9],[1,1],"untranslated"], [[9,10],[1,1],"untranslated"],
        [[10,15],[1,1],"untranslated"], [[15,16],[1,1],"untranslated"], [[16,22],[1,1],"untranslated"],
        [[22,23],[1,1],"untranslated"],
        [[23,23],[1,2],"untranslated"], # space in draft
        [[23,26],[2,3],"suggestion"], # second and
        [[26,27],[3,3],"untranslated"],[[27,31],[3,3],"untranslated"],[[31,32],[3,3],"untranslated"],
        [[32,32],[3,4],"untranslated"],
        [[32,34],[4,6],"suggestion"], # of
        [[34,35],[6,6],"untranslated"],[[35,41],[6,6],"untranslated"],[[41,43],[6,6],"untranslated"],
        [[43,43],[6,7],"untranslated"], # space in draft b/w me and last a
        [[43,46],[7,7],"untranslated"],[[46,47],[6,6],"untranslated"],[[47,53],[6,6],"untranslated"],
        [[53,54],[6,6],"untranslated"],[[54,59],[6,6],"untranslated"],[[59,60],[6,6],"untranslated"],
        [[60,65],[6,6],"untranslated"],[[65,67],[6,6],"untranslated"],
        [[67,67],[6,7],"untranslated"], # same space as above
        [[67,70],[7,8],"suggestion"], # last a
        [[70,71],[8,8],"untranslated"],[[71,76],[8,8],"untranslated"],[[76,77],[8,8],"untranslated"],
        [[77,82],[8,8],"untranslated"],[[82,83],[8,8],"untranslated"],[[83,87],[8,8],"untranslated"],
        [[87,88],[8,8],"untranslated"]]
    }
```

Corrected draftmeta
```
    {
      "sentenceId": "41001003",
      "surrogateId": "MAT 1:3",
      "sentence": "And Judas begat Phares and Zara of Thamar; and Phares begat Esrom; and Esrom begat Aram;",
      "draft": "a a me a",
      "draftMeta":[
        [[0,3],[0,1],"suggestion"], # and
        [[3,4],[1,1],"untranslated"], [[4,9],[1,1],"untranslated"], [[9,10],[1,1],"untranslated"],
        [[10,15],[1,1],"untranslated"], [[15,16],[1,1],"untranslated"], [[16,22],[1,1],"untranslated"],
        [[22,23],[1,1],"untranslated"],
        [[23,23],[1,2],"untranslated"], # space in draft
        [[23,26],[2,3],"suggestion"], # second and
        [[26,27],[3,3],"untranslated"],[[27,31],[3,3],"untranslated"],[[31,32],[3,3],"untranslated"],
        [[32,32],[3,4],"untranslated"],
        [[32,34],[4,6],"suggestion"], # of
        [[34,35],[6,6],"untranslated"],[[35,41],[6,6],"untranslated"],[[41,43],[6,6],"untranslated"],
#         [[43,43],[6,7],"untranslated"], # space in draft b/w me and last a
        [[43,46],[6,6],"untranslated"], # changed [7,7] to [6,6]
        [[46,47],[6,6],"untranslated"],[[47,53],[6,6],"untranslated"],
        [[53,54],[6,6],"untranslated"],[[54,59],[6,6],"untranslated"],[[59,60],[6,6],"untranslated"],
        [[60,65],[6,6],"untranslated"],[[65,67],[6,6],"untranslated"],
        [[67,67],[6,7],"untranslated"], # same space as above
        [[67,70],[7,8],"suggestion"], # last a
        [[70,71],[8,8],"untranslated"],[[71,76],[8,8],"untranslated"],[[76,77],[8,8],"untranslated"],
        [[77,82],[8,8],"untranslated"],[[82,83],[8,8],"untranslated"],[[83,87],[8,8],"untranslated"],
        [[87,88],[8,8],"untranslated"]]
    }
```

There might some bug in the UI code which lead to the duplicate entry for space and out-of-sequence value of [7,7] instead of [6,6]

When I run the suggestion API after the above two changes I get this repsonse, which looks correct to me
```
[
    {
        'sentenceId': 41001001, 
        'surrogateId': 'MAT 1:1', 
        'sentence': 'And Judas begat Phares and Zara of Thamar; and Phares begat Esrom; and Esrom begat Aram;', 
        'draft': 'a a me a a', 
        'draftMeta': [
            [[0, 3], [0, 1], 'suggestion'], # and -> a
            [[3, 4], [1, 1], 'untranslated'], [[4, 9], [1, 1], 'untranslated'], [[9, 10], [1, 1], 'untranslated'],
            [[10, 15], [1, 1], 'untranslated'], [[15, 16], [1, 1], 'untranslated'], [[16, 22], [1, 1], 'untranslated'], 
            [[22, 23], [1, 1], 'untranslated'], 
            [[23, 23], [1, 2], 'untranslated'], # space in draft
            [[23, 26], [2, 3], 'suggestion'], # and -> a
            [[26, 27], [3, 3], 'untranslated'], [[27, 31], [3, 3], 'untranslated'], [[31, 32], [3, 3], 'untranslated'], 
            [[32, 32], [3, 4], 'untranslated'], # space in draft
            [[32, 34], [4, 6], 'suggestion'], # of -> me
            [[34, 35], [6, 6], 'untranslated'], [[35, 41], [6, 6], 'untranslated'], [[41, 43], [6, 6], 'untranslated'],
            [[43, 43], [6, 7], 'untranslated'], # space in draft
            [[43, 46], [7, 8], 'suggestion'], # and -> a
            [[46, 47], [8, 8], 'untranslated'], [[47, 53], [8, 8], 'untranslated'], [[53, 54], [8, 8], 'untranslated'],
            [[54, 59], [8, 8], 'untranslated'], [[59, 60], [8, 8], 'untranslated'], [[60, 65], [8, 8], 'untranslated'],
            [[65, 67], [8, 8], 'untranslated'], 
            [[67, 67], [8, 9], 'untranslated'], # space in draft
            [[67, 70], [9, 10], 'suggestion'], # and -> a
            [[70, 71], [10, 10], 'untranslated'], [[71, 76], [10, 10], 'untranslated'], [[76, 77], [10, 10], 'untranslated'],
            [[77, 82], [10, 10], 'untranslated'], [[82, 83], [10, 10], 'untranslated'], [[83, 87], [10, 10], 'untranslated'],
            [[87, 88], [10, 10], 'untranslated']]
    }
]
```

**Comment by kavitharaju** [comment]
@ashish-garg-25  closing this issue for now. If you need further discussion on this please feel free to reopen
