### ISSUE TITLE
changes / new APIs required for Glossary

### ISSUE THREAD

**Issue by LijuJacob08** [Bridgeconn/vachan-api#502]
Issues-
-we can't list the glossary words with current [api](https://stagingapi.vachanengine.org/docs#/Nlp/get_glossary_v2_nlp_gloss_get) (as the token is a required field).

-there is no PUT call as well.(for editing the Glossary)

**Comment by LijuJacob08** [comment]
Hi Kavitha ,
can we that total row count value in our response[for the new [api](https://stagingapi.vachanengine.org/docs#/Nlp/get_glossary_entries_v2_nlp_gloss_entries_get)]..? this will be helpful for me to implement serverside pagination.
thanks

**Comment by LijuJacob08** [comment]
Adding one more to the list:-
can we have token list only query for the glossary something similary to word_list_only available for dictionary.

have one question ->do we have active and inactive tokens here as well like we have it for dictionary words?

**Comment by kavitharaju** [comment]
- [x] new GET list of glossary entires
- [x] new GET count of total glossary entries, with option to include/exclude inactive ones
- [x] change the POST api for learn gloss to not add metadata in a different entry but itself.
- [x] new PUT api to edit glossary items
- [x] new DELETE API for glossary items
