### ISSUE TITLE
change required in GET dictionary word API

### ISSUE THREAD

**Issue by LijuJacob08** [Bridgeconn/vachan-api#508]
in the current [API](https://stagingapi.vachanengine.org/docs#/Dictionaries/get_dictionary_word_v2_dictionaries__source_name__get) when we set Active query as "**--**"  in response we only get response with Active words (ie Active = 'true').
**change required**- it would be good ,if we get both active as well as inactive words when we specifying-"**--**"

**Comment by kavitharaju** [comment]
@LijuJacob08  is the implementation for this requirement satisfactory? Can this issue be closed?

**Comment by LijuJacob08** [comment]
hi,
yes, the requirement was met. This issue can be closed now. 
thank you.
