### ISSUE TITLE
Refactor APIs

### ISSUE THREAD

**Issue by joelthe1** [Bridgeconn/vachan-api#51]
There is some technical debt that we hope to pay back by going through the current version of the APIs and attempt to restructure, cleanup and reduce redundancy where possible.

**Comment by kavitharaju** [comment]
Use proper role names in DB. Use :
- Super Admin instead of current 'sa'
- AgMT Admin instead of current 'ad'
- AgMT Translator instead of current 'm'

**Comment by kavitharaju** [comment]
Use PK column names properly as `audio_bible_id`, `bible_video_id` and `bible_book_name_id` instead of just `id` in corresponding tables.

Make sure this pattern is followed in dynamically created tables like dictionaries.

**Comment by kavitharaju** [comment]
Rename the 'status' column in the source table to `active` so that the meaning is better conveyed.
Also rename the `status` columns of audio_bible and bible_video tables to a more understandable name like `available`
