### ISSUE TITLE
Delete of deleted contents

### ISSUE THREAD

**Issue by kavitharaju** [Bridgeconn/vachan-api#526]
1. The contents deleted from tables are now moved to a deleted items table. This table can be cleanup periodically by super Admin to save space.
2. The test runs as well as deletion of sources, leave dangling tables as residue. These are also to be removed upon removing contents from the deleted_items table

**Comment by shimilgithub** [comment]
### Testing results of database clean-up
- **Test 1** 

_Action:_ Created dynamic tables by running bible tests and tried to delete all dangling tables (does not have an existing source) through swagger.  

_Result:_ **Test Passed**. All the dangling tables generated by “test_bible” are removed. 

- **Test 2:** 

_Action:_ Created dynamic tables by running bible tests. Wrote testcase for creating and deleting a language (or any metacontent resource which does not create dynamic table) and executed this test.  

_Result:_ **Test Passed**. All the dangling tables generated by “test_bible” are removed. 

- **Test 3:** 

_Action:_  Wrote testcase for creating and deleting a commentary (This will create dynamic tables) and tried to remove those dangling tables. 

_Result:_  **Test Failed**. 

Code get freeze while running this testcase at the line of “delete operation” (conn.execute(f"DROP TABLE {table_name} CASCADE;"). 

**Reason Identified:** 

The table which is trying to delete (in test case) is in use. Hence the database is preventing from deleting the table, and the query could get stuck waiting for a response from the database. 

Checked if there is any lock on the table using  pg_stat_activity  and identified that the connection is holding a lock on the table which need to delete. 

Tried to terminate the query by running the pg_terminate_backend() function with the corresponding pid value but it closes the entire connection.
