### ISSUE TITLE
Suggestion API showing blank response after adding translation for some tokens

### ISSUE THREAD

**Issue by ashish-garg-25** [Bridgeconn/vachan-api#542]
I am getting issues in linking translation with token in ISL project. I have attached API call for both Draft API and the response i am getting.

**Payload**
PUT Call
API URL - https://islstagingapi.vachanengine.org/v2/translation/project/draft?project_id=100000
`{
    "draft": "they this",
    "draftMeta": [
        [
            [
                0,
                4
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                4,
                5
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                5,
                10
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                10,
                11
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                11,
                24
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                24,
                25
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                25,
                29
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                29,
                30
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                30,
                32
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                32,
                33
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                33,
                37
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                37,
                38
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                38,
                42
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                42,
                43
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                43,
                45
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                45,
                46
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                46,
                58
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                58,
                59
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                59,
                63
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                63,
                65
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                65,
                68
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                68,
                69
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                69,
                77
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                77,
                78
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                78,
                82
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                82,
                83
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                83,
                87
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                87,
                88
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                88,
                93
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                93,
                94
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                94,
                105
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                105,
                106
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                106,
                111
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                111,
                112
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                112,
                119
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                119,
                120
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                132,
                133
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                125,
                128
            ],
            [
                5,
                9
            ],
            "confirmed"
        ],
        [
            [
                129,
                132
            ],
            [
                0,
                4
            ],
            "confirmed"
        ]
    ],
    "sentenceId": 57001002
}`

**Response**
PUT call
API URL - https://islstagingapi.vachanengine.org/v2/translation/project/suggestions?project_id=100000&sentence_id_list=57001002
{
    "error": "Requested Content Not Available",
    "details": "Tokenization: token, does not, not found in sentence: This faith and knowledge make us sure that we have eternal life. God promised that life to us before time began—and God does not lie."
}

**Comment by kavitharaju** [comment]
@ashish-garg-25 We hear you are facing an issue like this
> the verse that has multiple alignments not displaying after Save

Is this the same problem reported above?

**Comment by ashish-garg-25** [comment]
Yes @kavitharaju
