### ISSUE TITLE
Last modified date showing incorrectly

### ISSUE THREAD

**Issue by AnnCherianA** [Bridgeconn/vachan-api#563]
Issue description : The last modified date of a project is currently showing the date the user added a book to the project 
Expected result : The last modified date is supposed to show the date when the user last modified the translation in the project 

Link to the UI issue in gitlab : https://gitlab.bridgeconn.com/software/research/sign-language/sign-translation-assistant/-/issues/118

This issue will be picked up later for enhancement and is of low priority now, as discussed in the  ISL team meeting

**Comment by AnnCherianA** [comment]
![image](https://github.com/Bridgeconn/vachan-api/assets/74647279/a1ffd72b-2e81-4e0f-9ae1-d5ba463f0aa4)

**Comment by shimilgithub** [comment]
Shows `GMT` timezone instead of `IST`
