### ISSUE TITLE
changes in GET-v2/nlp/gloss-entries

### ISSUE THREAD

**Issue by LijuJacob08** [Bridgeconn/vachan-api#566]
currently we don't have **tmID** in [GET -/v2/nlp/gloss](https://api.vachanengine.org/docs#/Nlp/get_glossary_v2_nlp_gloss_get)'s response , which is a required field and need it  while updating the gloss data using [PUT](https://api.vachanengine.org/docs#/Nlp/update_glossary_v2_nlp_gloss_put) call.

**Comment by LijuJacob08** [comment]
sorry- i'm using -https://api.vachanengine.org/docs#/Nlp/get_glossary_entries_v2_nlp_gloss_entries_get
 need **tmID** value in the **nlp/gloss-entries** api's response

**Comment by kavitharaju** [comment]
If we are changing, ideally we should make similar fields in all applicable places. So I guess both these APIs may need new tmId field

**Comment by shimilgithub** [comment]
-https://api.vachanengine.org/docs#/Nlp/get_glossary_entries_v2_nlp_gloss_entries_get already has `tmId` in response

**Comment by kavitharaju** [comment]
Oh, now that I look at it, adding `tmId` is not feasible in the [/v2/nlp/gloss](https://api.vachanengine.org/docs#/Nlp/get_glossary_v2_nlp_gloss_get) API as it is a collated result from multiple translation memory entries.

So, I guess this issue can be closed, right @LijuJacob08 ? The version [used by ISL app](https://islstagingapi.vachanengine.org/docs#/Nlp/get_glossary_entries_v2_nlp_gloss_entries_get) is not latest, that is what caused the confusion

**Comment by LijuJacob08** [comment]
agreed might be because when i was trying it - was getting [
    {
        "token": "call",
        "translation": "",
        "frequency": 0,
        "metaData": {
            "videoUrl": ""
        }
    },
    {
        "token": "with",
        "translation": "together",
        "frequency": 0,
        "metaData": {
            "videoUrl": ""
        }
] as response. 
we can close it . 
just wanted to know which release it's part of so that wont miss it ?

**Comment by shimilgithub** [comment]
> agreed might be because when i was trying it - was getting [ { "token": "call", "translation": "", "frequency": 0, "metaData": { "videoUrl": "" } }, { "token": "with", "translation": "together", "frequency": 0, "metaData": { "videoUrl": "" } ] as response. we can close it . just wanted to know which release it's part of so that wont miss it ?

Its available from  [2.0.0-beta.5 release](https://github.com/Bridgeconn/vachan-api/releases/tag/v2.0.0-beta.5)
