### ISSUE TITLE
Upload translated token API

### ISSUE THREAD

**Issue by Joel-C-Johnson** [Bridgeconn/vachan-api#59]
## User Story

As a user/admin/super admin, I need to able to upload a translated token file from an excel... So need an API to takes the JSON data from UI

json format sample

json [ {…}, {…} ]

[
0 : { "Token": "God ", "Translation": "esho", "Senses": "mashea"},
1 : {"Token": "Love", "Translation": "kathal", "Senses": "pranayam"}
]

**Comment by kavitharaju** [comment]
As you have shown an array I assume that the correct structure of input JOSN will be, 
[
 { "Token": "God ", "Translation": "esho", "Senses": "mashea"},
 {"Token": "Love", "Translation": "kathal", "Senses": "pranayam"}
]

without the keys, 0 , 1 etc you showed in the example.
Is this correct?

**Comment by Joel-C-Johnson** [comment]
yeah, it will be a list of objects...
eg :  [ {…}, {…} ]

**Comment by kavitharaju** [comment]
new API url : `"/v1/autographamt/projects/bulktranslations"`
inputs: projectId, tokenTranslations

Sample input data 
```
"projectId":57,
"tokenTranslations":
[
	{"token": "അംഗങ്ങളോടോ",
	"translation":"to members",
	"senses": []},
	{"token": "അംഗങ്ങൾ",
	"translation":"members",
	"senses": []},
	{"token": "അംഗഹീനനായിട്ടോ",
	"translation":"without an organ",
	"senses": []}
]
}
```
Please note that senses should be an array of strings.

**Comment by Joel-C-Johnson** [comment]
> new API url : `"/v1/autographamt/projects/bulktranslations"`
> inputs: projectId, tokenTranslations
> 
> Sample input data
> 
> ```
> {
> "projectId":57,
> "tokenTranslations":
> [
> 	{"token": "അംഗങ്ങളോടോ",
> 	"translation":"to members",
> 	"senses": ['to the members', 'to organs', 'is it to members']},
> 	{"token": "അംഗങ്ങൾ",
> 	"translation":"members",
> 	"senses": []},
> 	{"token": "അംഗഹീനനായിട്ടോ",
> 	"translation":"without an organ",
> 	"senses": []}
> ]
> }
> ```
> 
> Please note that senses should be an array of strings.

as am using an npm package to convert data into JSON from excel, am not able to make the values of the senses into an array of strings.  one single line of code help to convert the excel data into JSON. ("XLSX.utils.sheet_to_json(worksheet)") and am getting the below data if I add more senses separated by commas(,) in excel cell. 
[ {"token": "അംഗങ്ങളോടോ",
	"translation":"to members",
	"senses": "to the members, to organs, is it to members" }
]
So if you can take the value of that sense as a string a separate with commas and u can able to make an array of strings. if that works it will be easy..

**Comment by kavitharaju** [comment]
The senses was kept an array in accordance with the already existing API `/v1/autographamt/projects/translations`
which takes one token, its translation and senses and add them to DB.

Also I am of the opinion it should be kept as array, instead of making it comma seperated string, as the actual content is expected to be array.
