### ISSUE TITLE
After hitting draft API translated token is not showing

### ISSUE THREAD

**Issue by ashish-garg-25** [Bridgeconn/vachan-api#602]
We are getting issues saving translation in some scenarios.
Tried with Genesis of ERV version
when trying to save the token in draft indices is going correctly as per the demo of ISL and in the draft API response it is coming correct but after making a suggestion call draft word is not there. I have attached the payload, the response of the Draft API, and the response of the suggestion API.

Draft API Payload
`{
    "draft": "crete god",
    "draftMeta": [
        [
            [
                3,
                4
            ],
            [
                0,
                0
            ],
            "untranslated"
        ],
        [
            [
                4,
                11
            ],
            [
                0,
                5
            ],
            "suggestion"
        ],
        [
            [
                11,
                12
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                12,
                19
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                19,
                20
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                20,
                33
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                33,
                35
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                35,
                37
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                37,
                38
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                38,
                43
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                43,
                44
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                0,
                3
            ],
            [
                6,
                9
            ],
            "confirmed"
        ]
    ],
    "sentenceId": 1001001
}`

Draft Response 
`{
    "sentenceId": 1001001,
    "surrogateId": "gen 1:1",
    "sentence": "God created the sky and the earth. At first,",
    "draft": "crete god",
    "draftMeta": [
        [
            [
                3,
                4
            ],
            [
                0,
                0
            ],
            "untranslated"
        ],
        [
            [
                4,
                11
            ],
            [
                0,
                5
            ],
            "suggestion"
        ],
        [
            [
                11,
                12
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                12,
                19
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                19,
                20
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                20,
                33
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                33,
                35
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                35,
                37
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                37,
                38
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                38,
                43
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                43,
                44
            ],
            [
                9,
                9
            ],
            "untranslated"
        ],
        [
            [
                0,
                3
            ],
            [
                6,
                9
            ],
            "confirmed"
        ]
    ]
}`

Suggestion API response
`[
    {
        "sentenceId": 1001001,
        "surrogateId": "gen 1:1",
        "sentence": "God created the sky and the earth. At first,",
        "draft": "crete",
        "draftMeta": [
            [
                [
                    3,
                    4
                ],
                [
                    0,
                    0
                ],
                "untranslated"
            ],
            [
                [
                    4,
                    11
                ],
                [
                    0,
                    5
                ],
                "suggestion"
            ],
            [
                [
                    35,
                    37
                ],
                [
                    5,
                    5
                ],
                "untranslated"
            ],
            [
                [
                    37,
                    38
                ],
                [
                    5,
                    5
                ],
                "untranslated"
            ],
            [
                [
                    38,
                    43
                ],
                [
                    5,
                    5
                ],
                "untranslated"
            ],
            [
                [
                    43,
                    44
                ],
                [
                    5,
                    5
                ],
                "untranslated"
            ],
            [
                [
                    20,
                    33
                ],
                [
                    6,
                    6
                ],
                "untranslated"
            ],
            [
                [
                    33,
                    35
                ],
                [
                    6,
                    6
                ],
                "untranslated"
            ],
            [
                [
                    0,
                    3
                ],
                [
                    6,
                    9
                ],
                "confirmed"
            ],
            [
                [
                    12,
                    19
                ],
                [
                    7,
                    7
                ],
                "untranslated"
            ],
            [
                [
                    19,
                    20
                ],
                [
                    7,
                    7
                ],
                "untranslated"
            ],
            [
                [
                    11,
                    12
                ],
                [
                    8,
                    8
                ],
                "untranslated"
            ]
        ]
    }
]`

**Comment by kavitharaju** [comment]
The draft meta data you are passing doesn't account for the space between the words crete and god.
Adding an entry, `[[11,11],[5,6],"untranslated"]`, seems to be fixing it. 
How do you want to go about this? Fix it from UI or handle from backend?

**Comment by ashish-garg-25** [comment]
@kavitharaju 
I have tried same thing in other verse too. but in those it is working properly without space too
i have attached payload of same

`[
    {
        "draft": "the christ government",
        "draftMeta": [
            [
                [
                    0,
                    3
                ],
                [
                    0,
                    3
                ],
                "suggestion"
            ],
            [
                [
                    3,
                    4
                ],
                [
                    3,
                    3
                ],
                "untranslated"
            ],
            [
                [
                    13,
                    14
                ],
                [
                    3,
                    3
                ],
                "untranslated"
            ],
            [
                [
                    14,
                    27
                ],
                [
                    3,
                    3
                ],
                "untranslated"
            ],
            [
                [
                    27,
                    28
                ],
                [
                    3,
                    3
                ],
                "untranslated"
            ],
            [
                [
                    28,
                    36
                ],
                [
                    3,
                    3
                ],
                "untranslated"
            ],
            [
                [
                    36,
                    37
                ],
                [
                    3,
                    3
                ],
                "untranslated"
            ],
            [
                [
                    37,
                    37
                ],
                [
                    3,
                    3
                ],
                "untranslated"
            ],
            [
                [
                    4,
                    4
                ],
                [
                    3,
                    4
                ],
                "untranslated"
            ],
            [
                [
                    37,
                    43
                ],
                [
                    4,
                    10
                ],
                "confirmed"
            ],
            [
                [
                    43,
                    45
                ],
                [
                    21,
                    21
                ],
                "untranslated"
            ],
            [
                [
                    52,
                    53
                ],
                [
                    21,
                    21
                ],
                "untranslated"
            ],
            [
                [
                    53,
                    59
                ],
                [
                    21,
                    21
                ],
                "untranslated"
            ],
            [
                [
                    59,
                    60
                ],
                [
                    21,
                    21
                ],
                "untranslated"
            ],
            [
                [
                    45,
                    48
                ],
                [
                    11,
                    21
                ],
                "confirmed"
            ]
        ],
        "sentenceId": 42001001
    }
]`

**Comment by kavitharaju** [comment]
The first one seems to be a corner case which leads to the issue. Earlier we were not checking if all portions of the draft were represented by metadata segment, which lead the back-end to accept them as input, but later run into the issue when running suggestions on it. To prevent that, in the latest PR, we  are adding a validation for metadata, so it can be caught early on.
