### ISSUE TITLE
Validation issue in draftMeta

### ISSUE THREAD

**Issue by ashish-garg-25** [Bridgeconn/vachan-api#628]
We have added space but in some scenario we are still getting validation issue.
i am attaching both payload (working in one verse and not working in other verse) also attaching relevant response 

**Not working Payload**
ENDPOINT - https://islstagingapi.vachanengine.org/v2/translation/project/draft?project_id=100088
`[
    {
        "draft": "paul apostle god trust",
        "draftMeta": [
            [
                [
                    0,
                    4
                ],
                [
                    0,
                    4
                ],
                "suggestion"
            ],
            [
                [
                    4,
                    6
                ],
                [
                    4,
                    4
                ],
                "untranslated"
            ],
            [
                [
                    6,
                    15
                ],
                [
                    4,
                    4
                ],
                "untranslated"
            ],
            [
                [
                    15,
                    16
                ],
                [
                    4,
                    4
                ],
                "untranslated"
            ],
            [
                [
                    22,
                    23
                ],
                [
                    4,
                    4
                ],
                "untranslated"
            ],
            [
                [
                    23,
                    29
                ],
                [
                    4,
                    4
                ],
                "untranslated"
            ],
            [
                [
                    29,
                    30
                ],
                [
                    4,
                    4
                ],
                "untranslated"
            ],
            [
                [
                    30,
                    30
                ],
                [
                    4,
                    5
                ],
                "untranslated"
            ],
            [
                [
                    30,
                    37
                ],
                [
                    5,
                    12
                ],
                "suggestion"
            ],
            [
                [
                    37,
                    38
                ],
                [
                    12,
                    12
                ],
                "untranslated"
            ],
            [
                [
                    38,
                    46
                ],
                [
                    12,
                    12
                ],
                "untranslated"
            ],
            [
                [
                    46,
                    47
                ],
                [
                    12,
                    12
                ],
                "untranslated"
            ],
            [
                [
                    47,
                    53
                ],
                [
                    12,
                    12
                ],
                "untranslated"
            ],
            [
                [
                    53,
                    55
                ],
                [
                    12,
                    12
                ],
                "untranslated"
            ],
            [
                [
                    55,
                    67
                ],
                [
                    12,
                    12
                ],
                "untranslated"
            ],
            [
                [
                    67,
                    68
                ],
                [
                    12,
                    12
                ],
                "untranslated"
            ],
            [
                [
                    68,
                    74
                ],
                [
                    12,
                    12
                ],
                "untranslated"
            ],
            [
                [
                    74,
                    75
                ],
                [
                    12,
                    12
                ],
                "untranslated"
            ],
            [
                [
                    75,
                    75
                ],
                [
                    12,
                    13
                ],
                "untranslated"
            ],
            [
                [
                    75,
                    80
                ],
                [
                    17,
                    22
                ],
                "suggestion"
            ],
            [
                [
                    80,
                    81
                ],
                [
                    22,
                    22
                ],
                "untranslated"
            ],
            [
                [
                    81,
                    87
                ],
                [
                    22,
                    22
                ],
                "untranslated"
            ],
            [
                [
                    87,
                    90
                ],
                [
                    22,
                    22
                ],
                "untranslated"
            ],
            [
                [
                    90,
                    95
                ],
                [
                    22,
                    22
                ],
                "untranslated"
            ],
            [
                [
                    95,
                    96
                ],
                [
                    22,
                    22
                ],
                "untranslated"
            ],
            [
                [
                    96,
                    105
                ],
                [
                    22,
                    22
                ],
                "untranslated"
            ],
            [
                [
                    105,
                    106
                ],
                [
                    22,
                    22
                ],
                "untranslated"
            ],
            [
                [
                    106,
                    115
                ],
                [
                    22,
                    22
                ],
                "untranslated"
            ],
            [
                [
                    115,
                    116
                ],
                [
                    22,
                    22
                ],
                "untranslated"
            ],
            [
                [
                    116,
                    128
                ],
                [
                    22,
                    22
                ],
                "untranslated"
            ],
            [
                [
                    128,
                    130
                ],
                [
                    22,
                    22
                ],
                "untranslated"
            ],
            [
                [
                    130,
                    135
                ],
                [
                    22,
                    22
                ],
                "untranslated"
            ],
            [
                [
                    135,
                    136
                ],
                [
                    22,
                    22
                ],
                "untranslated"
            ],
            [
                [
                    136,
                    143
                ],
                [
                    22,
                    22
                ],
                "untranslated"
            ],
            [
                [
                    143,
                    144
                ],
                [
                    22,
                    22
                ],
                "untranslated"
            ],
            [
                [
                    144,
                    158
                ],
                [
                    22,
                    22
                ],
                "untranslated"
            ],
            [
                [
                    158,
                    159
                ],
                [
                    22,
                    22
                ],
                "untranslated"
            ],
            [
                [
                    19,
                    22
                ],
                [
                    13,
                    16
                ],
                "confirmed"
            ],
            [
                [
                    0,
                    0
                ],
                [
                    16,
                    17
                ],
                "untranslated"
            ]
        ],
        "sentenceId": 57001001
    }
]`

**Error Message**
{
    "error": "Unprocessable Data",
    "details": "Incorrect metadata:All portions of the draft should have a draftmeta segment showing its status. Expecting a draft segment starting with 9"
}

**Working Payload**
ENDPOINT - https://islstagingapi.vachanengine.org/v2/translation/project/draft?project_id=100087
`[
    {
        "draft": "own say lazy",
        "draftMeta": [
            [
                [
                    0,
                    3
                ],
                [
                    0,
                    0
                ], "untranslated"
            ],
            [
                [
                    3,
                    4
                ],
                [
                    0,
                    0
                ], "untranslated"
            ],
            [
                [
                    4,
                    18
                ],
                [
                    0,
                    0
                ], "untranslated"
            ],
            [
                [
                    18,
                    20
                ],
                [
                    0,
                    0
                ], "untranslated"
            ],
            [
                [
                    20,
                    29
                ],
                [
                    0,
                    0
                ], "untranslated"
            ],
            [
                [
                    29,
                    30
                ],
                [
                    0,
                    0
                ], "untranslated"
            ],
            [
                [
                    30,
                    38
                ],
                [
                    0,
                    0
                ], "untranslated"
            ],
            [
                [
                    38,
                    39
                ],
                [
                    0,
                    0
                ], "untranslated"
            ],
            [
                [
                    39,
                    42
                ],
                [
                    0,
                    3
                ], "suggestion"
            ],
            [
                [
                    42,
                    44
                ],
                [
                    3,
                    3
                ], "untranslated"
            ],
            [
                [
                    44,
                    44
                ],
                [
                    3,
                    4
                ], "untranslated"
            ],
            [
                [
                    44,
                    48
                ],
                [
                    4,
                    7
                ], "suggestion"
            ],
            [
                [
                    48,
                    51
                ],
                [
                    7,
                    7
                ], "untranslated"
            ],
            [
                [
                    51,
                    58
                ],
                [
                    7,
                    7
                ], "untranslated"
            ],
            [
                [
                    58,
                    59
                ],
                [
                    7,
                    7
                ], "untranslated"
            ],
            [
                [
                    59,
                    69
                ],
                [
                    7,
                    7
                ], "untranslated"
            ],
            [
                [
                    69,
                    70
                ],
                [
                    7,
                    7
                ], "untranslated"
            ],
            [
                [
                    70,
                    70
                ],
                [
                    3,
                    3
                ], "untranslated"
            ],
            [
                [
                    75,
                    77
                ],
                [
                    7,
                    7
                ], "untranslated"
            ],
            [
                [
                    77,
                    81
                ],
                [
                    7,
                    7
                ], "untranslated"
            ],
            [
                [
                    81,
                    82
                ],
                [
                    7,
                    7
                ], "untranslated"
            ],
            [
                [
                    82,
                    88
                ],
                [
                    7,
                    7
                ], "untranslated"
            ],
            [
                [
                    88,
                    90
                ],
                [
                    7,
                    7
                ], "untranslated"
            ],
            [
                [
                    90,
                    90
                ],
                [
                    7,
                    7
                ], "untranslated"
            ],
            [
                [
                    90,
                    94
                ],
                [
                    8,
                    12
                ], "suggestion"
            ],
            [
                [
                    94,
                    95
                ],
                [
                    12,
                    12
                ], "untranslated"
            ],
            [
                [
                    95,
                    103
                ],
                [
                    12,
                    12
                ], "untranslated"
            ],
            [
                [
                    103,
                    105
                ],
                [
                    12,
                    12
                ], "untranslated"
            ],
            [
                [
                    0,
                    0
                ],
                [
                    7,
                    8
                ], "untranslated"
            ]
        ],
        "sentenceId": 57001012
    }
]`

@kavitharaju

**Comment by kavitharaju** [comment]
@ashish-garg-25 , please provide the source sentence too, so I can tinker with your data from my end

**Comment by ashish-garg-25** [comment]
For working draftMeta: One of the Cretans, a prophet of their own, said, “Cretans are always liars, evil beasts, lazy gluttons.”
For not working draftMeta: For this, i am not able to get the sentence as suggestion PUT api is throwing this error as before
ERROR: {
    "error": "Unprocessable Data",
    "details": "Incorrect metadata:Target segments [14, 17] and [16, 17] overlaps!"
}

I am attaching one more example of a non-working scenario where the verse is not gone 
**ENDPOINT**: https://islstagingapi.vachanengine.org/v2/translation/project/draft?project_id=100087
**SENTENCE**: They must be silenced, since they are upsetting whole families by teaching for shameful gain what they ought not to teach.
**ERROR**: {
    "error": "Unprocessable Data",
    "details": "Incorrect metadata:All portions of the draft should have a draftmeta segment showing its status. Expecting a draft segment starting with 9"
}
**PAYLOAD**:
`[
    {
        "draft": "they must they together your",
        "draftMeta": [
            [
                [
                    0,
                    4
                ],
                [
                    0,
                    4
                ],
                "suggestion"
            ],
            [
                [
                    4,
                    5
                ],
                [
                    4,
                    4
                ],
                "untranslated"
            ],
            [
                [
                    5,
                    5
                ],
                [
                    4,
                    5
                ],
                "untranslated"
            ],
            [
                [
                    5,
                    9
                ],
                [
                    5,
                    9
                ],
                "suggestion"
            ],
            [
                [
                    9,
                    10
                ],
                [
                    9,
                    9
                ],
                "untranslated"
            ],
            [
                [
                    10,
                    21
                ],
                [
                    9,
                    9
                ],
                "untranslated"
            ],
            [
                [
                    21,
                    23
                ],
                [
                    9,
                    9
                ],
                "untranslated"
            ],
            [
                [
                    23,
                    28
                ],
                [
                    9,
                    9
                ],
                "untranslated"
            ],
            [
                [
                    28,
                    29
                ],
                [
                    9,
                    9
                ],
                "untranslated"
            ],
            [
                [
                    29,
                    29
                ],
                [
                    9,
                    10
                ],
                "untranslated"
            ],
            [
                [
                    29,
                    33
                ],
                [
                    10,
                    14
                ],
                "suggestion"
            ],
            [
                [
                    33,
                    34
                ],
                [
                    14,
                    14
                ],
                "untranslated"
            ],
            [
                [
                    34,
                    47
                ],
                [
                    14,
                    14
                ],
                "untranslated"
            ],
            [
                [
                    47,
                    48
                ],
                [
                    14,
                    14
                ],
                "untranslated"
            ],
            [
                [
                    48,
                    53
                ],
                [
                    14,
                    14
                ],
                "untranslated"
            ],
            [
                [
                    53,
                    54
                ],
                [
                    14,
                    14
                ],
                "untranslated"
            ],
            [
                [
                    54,
                    54
                ],
                [
                    7,
                    7
                ],
                "untranslated"
            ],
            [
                [
                    62,
                    63
                ],
                [
                    14,
                    14
                ],
                "untranslated"
            ],
            [
                [
                    63,
                    74
                ],
                [
                    14,
                    14
                ],
                "untranslated"
            ],
            [
                [
                    74,
                    75
                ],
                [
                    14,
                    14
                ],
                "untranslated"
            ],
            [
                [
                    75,
                    87
                ],
                [
                    14,
                    14
                ],
                "untranslated"
            ],
            [
                [
                    87,
                    88
                ],
                [
                    14,
                    14
                ],
                "untranslated"
            ],
            [
                [
                    88,
                    92
                ],
                [
                    14,
                    14
                ],
                "untranslated"
            ],
            [
                [
                    92,
                    93
                ],
                [
                    14,
                    14
                ],
                "untranslated"
            ],
            [
                [
                    93,
                    93
                ],
                [
                    14,
                    14
                ],
                "untranslated"
            ],
            [
                [
                    93,
                    97
                ],
                [
                    15,
                    23
                ],
                "suggestion"
            ],
            [
                [
                    97,
                    98
                ],
                [
                    23,
                    23
                ],
                "untranslated"
            ],
            [
                [
                    98,
                    98
                ],
                [
                    23,
                    23
                ],
                "untranslated"
            ],
            [
                [
                    98,
                    102
                ],
                [
                    24,
                    28
                ],
                "suggestion"
            ],
            [
                [
                    102,
                    103
                ],
                [
                    28,
                    28
                ],
                "untranslated"
            ],
            [
                [
                    103,
                    108
                ],
                [
                    28,
                    28
                ],
                "untranslated"
            ],
            [
                [
                    108,
                    109
                ],
                [
                    28,
                    28
                ],
                "untranslated"
            ],
            [
                [
                    109,
                    121
                ],
                [
                    28,
                    28
                ],
                "untranslated"
            ],
            [
                [
                    121,
                    122
                ],
                [
                    28,
                    28
                ],
                "untranslated"
            ],
            [
                [
                    0,
                    0
                ],
                [
                    14,
                    15
                ],
                "untranslated"
            ],
            [
                [
                    1,
                    1
                ],
                [
                    23,
                    24
                ],
                "untranslated"
            ]
        ],
        "sentenceId": 57001011
    }
]`
@kavitharaju

**Comment by kavitharaju** [comment]
@ashish-garg-25 
There seems to be a bug in the draft Meta created from server after running the suggestions, which I am fixing. But I need clarifications on a few things:
1. You've said the `translation/project/draft` endpoint. But is it GET or PUT? From the payload I am assuming its PUT and you are not trying to use an older project that may have incorrect data before we had this validation in place.
2. In the first not working case, The error I get now is `{'error': 'Unprocessable Data', 'details': 'Incorrect metadata:Source segment [96, 105], is improper!'}` which makes sense to me as I see the input sentence is only 98 characters long.
3. In the 3rd example you shared there are segs with target indices `[ [ 5, 9 ], [ 5, 9 ], "suggestion" ]` indicating 5-9 of the target is a single segment and then you have `[ [ 54, 54 ], [ 7, 7 ], "untranslated" ]`, which doesn't seems to be correct to me.

**Comment by kavitharaju** [comment]
4. You have given this error
   ```
   {
       "error": "Unprocessable Data",
       "details": "Incorrect metadata:Target segments [14, 17] and [16, 17] overlaps!"
    }
    ```

But I can't figure out which API call gives it. My assumption is, if this was raised for an input where you did not pass in these incorrect segments, it was raised upon suggestion API call, not simple draft PUT. Which I have identified as a bug and is fixing. But if you passed it in, in the input of a draft PUT API, this is wrong data you are trying to save.

**Comment by ashish-garg-25** [comment]
1. We are using PUT API, We have tried in both new and old project
2. Let me check same
3. Okay i will remove draftMeta like these
4. This error is coming in suggestion API. While calling draft API and saving data it worked but in suggestion API it is breaking
@kavitharaju

**Comment by kavitharaju** [comment]
The fix for the bug identified in metadata created from server(happening in suggestion API call) will be available in beta.11.
