### ISSUE TITLE
FastAPI Upgrade

### ISSUE THREAD

**Issue by kavitharaju** [Bridgeconn/vachan-api#631]
- Fast API newer version available https://github.com/tiangolo/fastapi/releases/tag/0.100.0
- Other packages also have newer versions available: starllete, pydantic, pytest, SQLAlchemy, psycopg2
- Need to check which all versions are compatible with each other and bump to the latest possible versions

**Comment by shimilgithub** [comment]
https://github.com/tiangolo/fastapi/releases
