### ISSUE TITLE
Download tokens

### ISSUE THREAD

**Issue by Joel-C-Johnson** [Bridgeconn/vachan-api#64]
## User Story

As a user/admin/super admin, I need to able to download the " tokens, translated tokens and senses "  in an excel for each book in an excel... So need an API that returns the JSON in below format 
[
 [token,translation, senses, concordance, translationNotes, translationWords], 
 [token,translation, senses, concordance, translationNotes, translationWords],
 [token,translation, senses, concordance, translationNotes, translationWords],
]

**Comment by kavitharaju** [comment]
Wouldn't these information be enough to download as excel ?
```
[
[token,translation, senses],
[token,translation, senses],
[token,translation, senses],
]```

**Comment by Joel-C-Johnson** [comment]
> Wouldn't these information be enough to download as excel ?
> 
> ```
> [
> [token,translation, senses],
> [token,translation, senses],
> [token,translation, senses],
> ]```
> ```

yeah this format will help to download the files

**Comment by kavitharaju** [comment]
The API is implemented in the branch [bulk-DOWNLOAD-tokens](https://github.com/Bridgeconn/vachan-api/tree/bulk-DOWNLOAD-tokens).
The details are as follows:

GET method
URL: `/v1/tokentranslationlist/<projectId>/<book>` (somewhat similar to `/v1/tokenlist/<sourceId>/<book>` which fetches just the tokens of a book, without translations)
AUTH: Only accessible to a user who has been assigned that book in that project.
INPUT: projectId and 3 letter bookCode(lower or upper cases accepted)
SAMPLE OUTPUT:
```
[
 {'token': 'അകത്തേക്കു', 'translation': None, 'senses': None},
 {'token': 'അകത്ത്', 'translation': 'inside', 'senses': None},
 {'token': 'അകത്ത്', 'translation': 'inside', 'senses': ['into']},
 {'token': 'അകത്ത്', 'translation': 'inside', 'senses': None},
 {'token': 'അകത്ത് ചെന്ന്', 'translation': 'going inside', 'senses': None},
 {'token': 'അകന്നാണു', 'translation': None, 'senses': None},
 ...
]
```

**Comment by Joel-C-Johnson** [comment]
as we are using an npm module(xlsx) for downloading the file in an excel it takes a list as input.
eg:
var array = 
[ 
  [token,translation, senses],
  [token,translation, senses]
]

var ws_data = array
var ws = XLSX.utils.aoa_to_sheet(ws_data);

So if we get a JSON format that you have shown above I need to again loop all the tokens and need to make a list out of that. it may be a very slow process in the UI side.. so it would be good if you can make the JSON format that I have mentioned above.. And for senses join the list using a comma(,)... I will also give some eg below.
eg: 1

[
  ["token" ,"translation", "word1,word2" ],
  ["token", " " , [ ] ],
  ["token", "translation", null],
]

Note: you can give empty string(" ") or null if there is no value

**Comment by kavitharaju** [comment]
The output format has been changed to 
```
	[
	 ['token', null, null],
	 ['token', 'translation', null],
	 ['token', 'translation', 'senses1'],
	 ['token', 'translation', 'senses1,sense2'],
	 ['token', 'translation', null],
	 ['token', null, null],
	 ...
	]
```
Its an array or arrays now.
`null` values used when valuve not available.
senses are joined as a comma separated string
