### ISSUE TITLE
Project owner is not able to remove the project member

### ISSUE THREAD

**Issue by LijuJacob08** [Bridgeconn/vachan-api#683]
**Issue**:   was able to delete the project member as AgAdmin  but was not able to delete as projectOwner. 
Expected :as per the access rules  **"delete-user"** should work for **["SuperAdmin", "AgAdmin", "SanketMASTAdmin", "projectOwner"] users**

api used: https://api.vachanengine.org/v2/translation/project/user?project_id=100009&user_id=f12fd55f-04be-4e5f-b0e4-d95b18826dbb
Status: 403 Forbidden

**Comment by kavitharaju** [comment]
Can you provide more details on this.
What is the role of the user being deleted? What is the detailed error message you get from API?

**Comment by LijuJacob08** [comment]
**Project Name**: ERV_Test_5
**project Id**: 100009
**Project owner's userId**- d88fc090-9d7e-4abf-88cd-3af52c8a4be6
**Project Member's detail whom i was trying to delete** -
{
    "project_id": 100009,
    "userId": "f12fd55f-04be-4e5f-b0e4-d95b18826dbb",
    "userRole": "projectMember",
    "metaData": null,
    "active": true
}

**Response**:
{
  "error": "Permission Denied",
  "details": "Access Permission Denied for the URL"
}
![image](https://github.com/Bridgeconn/vachan-api/assets/93033055/0b5d3991-056a-4b1f-b35d-529b738e76f2)
