### ISSUE TITLE
Data Upload using APIs for Staging and Production Deployments

### ISSUE THREAD

**Issue by shimilgithub** [Bridgeconn/vachan-api#724]
Script for populating staging and production databases by integrating relevant APIs.

Sprint 4
------------------

- [x] Understanding existing code - 3 hours - time taken(5)
- [x] Upload resources - 3 hours- time taken(5)
- [x] Upload audio bibles - 3 hours-time taken(3)
- [x] upload parascriptuals - 3 hours-time taken(3)
- [x] upload commentry - 3 hours-time taken(3)
- [x] upload infographics - 3 hours-time taken(3)
- [x] upload bible video data - 3 hours-time taken(3)
- [x] Testing - 1 hour
- [x] PR review(Athulya,Shimil) - 1 hour
- [x] Review Fixes - 1 hour
- [x] Final review and merge(Shimil) - 30 mins

Sprint 5
------------------
 - [x] Implementing try catch except into code  - 5 hours
 - [x] auth token API - 5 hours
 - [x] final validation - 5 hours
 - [x] creating new schema - 3 hours
 - [x] integrating - 4hours
 - [x] Validation and verification (shimil and athulya) - 2 hours
 
 time taken - 19 hours
 
 
 
 Extra tasks added 
- [x] added new vocabulary data  - 4 hours
- [x] Added new bible data - 6 hours
- [x] New script to extract data in csv from large data dumps. - 6 hours

Sprint 6 
 - [x] Code change regarding new integration - 1.5  hours
 - [x] writing new readme file - 1.5  hours
 - [x] PR Review changes - 1 hours

time taken : 4 hours

**Comment by AthulyaMS** [comment]
- [x] make script changes - 3 hr
- [x] make csv of signbible video -5hr
- [x] testing with local db -4 hr
- [x] PR review -1 hr
- [x] Review fix -1 hr
