### ISSUE TITLE
Authentication for V2 

### ISSUE THREAD

**Issue by kavitharaju** [Bridgeconn/vachan-api#83]
We were using OAuth2 in V1. 
Are we planning to use the same in V2? Fastapi has [provisions to use OAuth.](https://fastapi.tiangolo.com/tutorial/security/first-steps/)

For security fastapi has more options [here](https://fastapi.tiangolo.com/advanced/security/oauth2-scopes/) and  [here](https://fastapi.tiangolo.com/advanced/security/)

@joelthe1 @RevantCI  @samuelanthrayose What are your thoughts on this?

**Comment by joelthe1** [comment]
Yes, OAuth2 looks like the right direction.
