### ISSUE TITLE
Update or Remove Makefile for Vachan API

### ISSUE THREAD

**Issue by shimilgithub** [Bridgeconn/vachan-api#845]
There is a [Makefile setup ](https://github.com/Bridgeconn/vachan-api/blob/version-2/makefile)created for installation in the Vachan API codebase. Since the code has been split into microservices and now resides in different repositories, the Makefile needs to be updated or removed from the codebase to reflect these changes.

**Comment by Joel-C-Johnson** [comment]
ETT - SP 18

- [x] Understand the codebase - 6hrs
- [x] work on the issue - 6hrs
- [x] testing - 4hrs
- [x]  PR - [846](https://github.com/Bridgeconn/vachan-api/pull/864) review (Revant) - 1hrs
- [x] PR fix - 2hrs

ATT - 12hrs

**Comment by Joel-C-Johnson** [comment]
- make files fixed 
- it only has the landing page - landing page link prodution
- Vachan Api Version 2 branch is not currently in development and all services have been moved to GitLab repo as microservices
- To run the microservies we can deploy using staging.yaml and prodution.yaml files
   ```git clone -b version-2 https://github.com/Bridgeconn/vachan-api.git```
   ```cd vachan-api/docker```
   ``` docker compose -f docker-compose-staging.yml --profile local-run up```
   or
   ```sudo -E  docker compose -f docker-compose-staging.yml --profile local-run up```
