### ISSUE TITLE
Remove Test Container from Vachan API Docker Compose

### ISSUE THREAD

**Issue by shimilgithub** [Bridgeconn/vachan-api#846]
There is a [container](https://github.com/Bridgeconn/vachan-api/blob/version-2/docker/docker-compose.yml#L144) in the Vachan API Docker Compose file designed to run tests.Since the code has been split into microservices and there are no longer any tests in the Vachan API, this container is no longer needed and should be removed.

**Comment by KetanKBaboo** [comment]
**Sp 18 (Ketan):-**

- [x] Local setup - (E.T - 2 hour) - (A.T - 1 hour)
- [x] Understand the task +  Discussion with Athulya (E.T - 1.5 hour) - (A.T - 1 hour)
- [x] Learn about github actions - (E.T - 2 hours) - (A.T. - 2 hours)
- [x] Work on the task - (E.T - 1 hour) - (A.T - 45min)
- [x] PR review(Athulya) - (E.T - 0.5 hour)
